# Generated by Django 5.0.1 on 2024-01-02 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='recpie',
            new_name='recipe',
        ),
    ]
